version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: symfony_php
    volumes:
      - ./app:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
      - "9000:9000"

  web:
    image: nginx:stable-alpine
    container_name: symfony_web
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      
    depends_on:
      - php
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: